INCLUDE(ExternalProject)

ExternalProject_Add(
    libSDL3_gfx

    DEPENDS libSDL3

    GIT_REPOSITORY https://github.com/etorth/SDL3_gfx.git
    GIT_TAG master

    GIT_SHALLOW TRUE
    GIT_SUBMODULES_RECURSE TRUE

    CMAKE_ARGS
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX=${SUPERBUILD_INSTALL_DIR}
        -DCMAKE_PREFIX_PATH=${SUPERBUILD_INSTALL_DIR}
        -DSDL3_INCLUDE_DIR=${SUPERBUILD_INSTALL_DIR}/include
        -DBUILD_SHARED_LIBS=OFF

    BUILD_BYPRODUCTS
        ${SUPERBUILD_INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}SDL3_gfx${CMAKE_STATIC_LIBRARY_SUFFIX}
)

ExternalProject_Get_Property(libSDL3_gfx INSTALL_DIR)

ADD_LIBRARY(SDL3_gfx::SDL3_gfx STATIC IMPORTED GLOBAL)
SET_TARGET_PROPERTIES(SDL3_gfx::SDL3_gfx PROPERTIES
    IMPORTED_LOCATION ${INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}SDL3_gfx${CMAKE_STATIC_LIBRARY_SUFFIX}
    INTERFACE_INCLUDE_DIRECTORIES ${INSTALL_DIR}/include
)
ADD_DEPENDENCIES(SDL3_gfx::SDL3_gfx libSDL3_gfx)
