INCLUDE(ExternalProject)

ExternalProject_Add(
    libSDL3_ttf

    DEPENDS libSDL3

    GIT_REPOSITORY https://github.com/libsdl-org/SDL_ttf.git
    GIT_TAG main

    GIT_SHALLOW TRUE
    GIT_SUBMODULES_RECURSE TRUE

    CMAKE_ARGS
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX=${SUPERBUILD_INSTALL_DIR}
        -DCMAKE_PREFIX_PATH=${SUPERBUILD_INSTALL_DIR}
        -DSDLTTF_VENDORED=ON
        -DBUILD_SHARED_LIBS=OFF

    BUILD_BYPRODUCTS
        ${SUPERBUILD_INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}SDL3_ttf${CMAKE_STATIC_LIBRARY_SUFFIX}
)

ADD_LIBRARY(SDL3_ttf::SDL3_ttf STATIC IMPORTED GLOBAL)
SET_TARGET_PROPERTIES(SDL3_ttf::SDL3_ttf PROPERTIES
    IMPORTED_LOCATION ${SUPERBUILD_INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}SDL3_ttf${CMAKE_STATIC_LIBRARY_SUFFIX}
    INTERFACE_INCLUDE_DIRECTORIES ${SUPERBUILD_INSTALL_DIR}/include
)
ADD_DEPENDENCIES(SDL3_ttf::SDL3_ttf libSDL3_ttf)
