INCLUDE(ExternalProject)

ExternalProject_Add(
    libSDL3_mixer

    DEPENDS libSDL3

    GIT_REPOSITORY https://github.com/libsdl-org/SDL_mixer.git
    GIT_TAG main

    GIT_SHALLOW TRUE
    GIT_SUBMODULES_RECURSE TRUE

    CMAKE_ARGS
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX=${SUPERBUILD_INSTALL_DIR}
        -DCMAKE_PREFIX_PATH=${SUPERBUILD_INSTALL_DIR}
        -DSDLMIXER_VENDORED=ON
        -DBUILD_SHARED_LIBS=OFF
        -DSDLMIXER_MIDI_NATIVE=OFF
        -DSDLMIXER_GME=OFF
        -DSDLMIXER_WAVPACK=OFF
        -DSDLMIXER_MOD=OFF
        -DSDLMIXER_MOD_XMP=OFF
        -DSDLMIXER_OPUS=OFF
        -DSDLMIXER_MP3_MPG123=OFF
        -DSDLMIXER_VORBIS_VORBISFILE=OFF
        -DSDLMIXER_FLAC_LIBFLAC=OFF

    BUILD_BYPRODUCTS
        ${SUPERBUILD_INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}SDL3_mixer${CMAKE_STATIC_LIBRARY_SUFFIX}
)

ADD_LIBRARY(SDL3_mixer::SDL3_mixer STATIC IMPORTED GLOBAL)
SET_TARGET_PROPERTIES(SDL3_mixer::SDL3_mixer PROPERTIES
    IMPORTED_LOCATION ${SUPERBUILD_INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}SDL3_mixer${CMAKE_STATIC_LIBRARY_SUFFIX}
    INTERFACE_INCLUDE_DIRECTORIES ${SUPERBUILD_INSTALL_DIR}/include
)
ADD_DEPENDENCIES(SDL3_mixer::SDL3_mixer libSDL3_mixer)
