INCLUDE(ExternalProject)

ExternalProject_Get_Property(libSDL3 INSTALL_DIR)
SET(SDL3_INSTALL_DIR ${INSTALL_DIR})

ExternalProject_Add(
    libSDL3_image

    DEPENDS libSDL3

    GIT_REPOSITORY https://github.com/libsdl-org/SDL_image.git
    GIT_TAG release-3.2.4

    GIT_SHALLOW TRUE
    GIT_SUBMODULES_RECURSE TRUE

    CMAKE_ARGS
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX=${SUPERBUILD_INSTALL_DIR}
        -DCMAKE_PREFIX_PATH=${SUPERBUILD_INSTALL_DIR}
        -DBUILD_SHARED_LIBS=OFF
        -DSDL3IMAGE_STATIC=ON
        -DSDL3IMAGE_SHARED=OFF
        -DSDLIMAGE_VENDORED=ON
        -DSDLIMAGE_AVIF=OFF
        -DSDLIMAGE_BMP=OFF
        -DSDLIMAGE_JPEG=OFF
        -DSDLIMAGE_WEBP=OFF
        -DSDLIMAGE_TIF=OFF

    BUILD_BYPRODUCTS
        ${SUPERBUILD_INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}SDL3_image${CMAKE_STATIC_LIBRARY_SUFFIX}
)

ExternalProject_Get_Property(libSDL3_image INSTALL_DIR)

ADD_LIBRARY(SDL3_image::SDL3_image STATIC IMPORTED GLOBAL)
SET_TARGET_PROPERTIES(SDL3_image::SDL3_image PROPERTIES
    IMPORTED_LOCATION ${INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}SDL3_image${CMAKE_STATIC_LIBRARY_SUFFIX}
    INTERFACE_INCLUDE_DIRECTORIES ${INSTALL_DIR}/include
)
ADD_DEPENDENCIES(SDL3_image::SDL3_image libSDL3_image)
