INCLUDE(ExternalProject)

ExternalProject_Add(
    libSDL3

    GIT_REPOSITORY https://github.com/libsdl-org/SDL.git
    GIT_TAG release-3.2.26

    GIT_SHALLOW TRUE

    CMAKE_ARGS
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
        -DBUILD_SHARED_LIBS=OFF
        -DSDL_STATIC=ON
        -DSDL_SHARED=OFF

    BUILD_BYPRODUCTS
        <INSTALL_DIR>/lib/${CMAKE_STATIC_LIBRARY_PREFIX}SDL3${CMAKE_STATIC_LIBRARY_SUFFIX}
)

ExternalProject_Get_Property(libSDL3 INSTALL_DIR)

ADD_LIBRARY(SDL3::SDL3 STATIC IMPORTED GLOBAL)
SET_TARGET_PROPERTIES(SDL3::SDL3 PROPERTIES
    IMPORTED_LOCATION ${INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}SDL3${CMAKE_STATIC_LIBRARY_SUFFIX}
    INTERFACE_INCLUDE_DIRECTORIES ${INSTALL_DIR}/include
)
ADD_DEPENDENCIES(SDL3::SDL3 libSDL3)
